

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

//Estrutura para armazenar os dados das pessoas
typedef struct {
    char nome[100];
    int idade;
} Pessoa;

//Estrutura para armazenar as métricas de cada algoritmo
typedef struct {
    long long comparacoes;
    long long trocas;
    double tempo_total;
} Metricas;

// Protótipos das funções de ordenação 
void bubbleSort(Pessoa arr[], int n, Metricas* m);
void selectionSort(Pessoa arr[], int n, Metricas* m);
void quickSort(Pessoa arr[], int baixo, int alto, Metricas* m);



void bubbleSort(Pessoa arr[], int n, Metricas* m) {
    
    m->comparacoes = 0;
    m->trocas = 0;
    int i,j;
    
    for (i = 0; i < n - 1; i++) {
        for ( j = 0; j < n - i - 1; j++) {
            //Incremento do numero de comparações
            m->comparacoes++;
            //Ordenando pelo nome usando strcmp
            if (strcmp(arr[j].nome, arr[j + 1].nome) > 0) {
                // Troca os elementos
                Pessoa temp = arr[j];
                arr[j] = arr[j + 1];
                arr[j + 1] = temp;
                //o numero de trocas é incrementado
                m->trocas++;
            }
        }
    }
}



void selectionSort(Pessoa arr[], int n, Metricas* m) {
    m->comparacoes = 0;
    m->trocas = 0;
	int i,j;
	
    for (i = 0; i < n - 1; i++) {
        int min_idx = i;
        for ( j = i + 1; j < n; j++) {
          
            m->comparacoes++;
            if (strcmp(arr[j].nome, arr[min_idx].nome) < 0) {
                min_idx = j;
            }
        }
        if (min_idx != i) {
            
            Pessoa temp = arr[min_idx];
            arr[min_idx] = arr[i];
            arr[i] = temp;
            
            m->trocas++;
        }
    }
}




void trocar(Pessoa* a, Pessoa* b, Metricas* m) {
    Pessoa t = *a;
    *a = *b;
    *b = t;
    m->trocas++;
}


int particionar(Pessoa arr[], int baixo, int alto, Metricas* m) {
    Pessoa pivo = arr[alto];
    int i = (baixo - 1);
	int j;
	
    for ( j = baixo; j <= alto - 1; j++) {
        m->comparacoes++;
        if (strcmp(arr[j].nome, pivo.nome) < 0) {
            i++;
            trocar(&arr[i], &arr[j], m);
        }
    }
    trocar(&arr[i + 1], &arr[alto], m);
    return (i + 1);
}


void quickSort(Pessoa arr[], int baixo, int alto, Metricas* m) {
    
    if (baixo == 0 && alto == (sizeof(arr)/sizeof(arr[0])) - 2) {
        m->comparacoes = 0;
        m->trocas = 0;
    }
    
    if (baixo < alto) {
        int pi = particionar(arr, baixo, alto, m);
        quickSort(arr, baixo, pi - 1, m);
        quickSort(arr, pi + 1, alto, m);
    }
}


void imprimirPessoas(Pessoa arr[], int n) {
	int i;
    for ( i = 0; i < n; i++) {
        printf("Nome: %s, Idade: %d\n", arr[i].nome, arr[i].idade);
    }
    printf("----------------------------------------\n");
}


int main() {
    
    Pessoa pessoas[] = {
    {"Livia Lopes", 45},
    {"Eloa Machado", 20},
    {"Laura Ribeiro", 21},
    {"Lorena Barbosa", 55},
    {"Theo Carvalho", 66},
    {"Livia Martins", 48},
    {"Camila Martins", 20},
    {"Samuel Tavares", 40},
    {"Heloisa Ribeiro", 33},
    {"Bernardo Freitas", 40},
    {"Rafael Correia", 78},
    {"Isabella Soares", 63},
    {"Lucas Tavares", 36},
    {"Manuela Mendes", 26},
    {"Fernando Ferreira", 56},
    {"Andre Campos", 66},
    {"Patricia Nascimento", 20},
    {"Laura Neves", 60},
    {"Helena Freitas", 50},
    {"Theo Cunha", 38},
    {"Francisco Cardoso", 47},
    {"Nicolas Fernandes", 55},
    {"Livia Peixoto", 21},
    {"Rafael Freitas", 78},
    {"Helena Viana", 65},
    {"Debora Rodrigues", 49},
    {"Carlos Viana", 63},
    {"Miguel Souza", 36},
    {"Theo Neves", 49},
    {"Isabel Vieira", 40},
    {"Jose Tavares", 68},
    {"Marcos Azevedo", 30},
    {"Yasmin Campos", 35},
    {"Andre Peixoto", 43},
    {"Theo Lopes", 47},
    {"Guilherme Dias", 57},
    {"Sofia Martins", 72},
    {"Enzo Rocha", 53},
    {"Camila Rocha", 37},
    {"Davi Rezende", 21},
    {"Bernardo Neves", 27},
    {"Laura Siqueira", 47},
    {"Valentina Peixoto", 58},
    {"Helena Melo", 52},
    {"Luiza Viana", 59},
    {"Yasmin Castro", 44},
    {"Lucas Pinto", 43},
    {"Isabella Melo", 70},
    {"Heitor Cunha", 75},
    {"Matheus Rezende", 24},
    {"Camila Castro", 33},
    {"Eloa Cunha", 41},
    {"Carlos Rocha", 24},
    {"Gael Siqueira", 51},
    {"Heitor Ribeiro", 48},
    {"Agatha Moreira", 45},
    {"Beatriz Siqueira", 26},
    {"Lorena Fernandes", 46},
    {"Helena Gomes", 39},
    {"Julia Mendes", 38},
    {"Maria Tavares", 28},
    {"Raimundo Peixoto", 52},
    {"Arthur Tavares", 68},
    {"Sofia Cunha", 20},
    {"Bernardo Lopes", 69},
    {"Helena Rocha", 79},
    {"Rebeca Vieira", 64},
    {"Patricia Viana", 52},
    {"Lucas Castro", 28},
    {"Nicolas Moura", 52},
    {"Livia Araujo", 72},
    {"Isabel Siqueira", 71},
    {"Antonio Peixoto", 20},
    {"Manuela Cunha", 61},
    {"Laura Carvalho", 54},
    {"Valentina Ferreira", 57},
    {"Camila Cardoso", 66},
    {"Eloa Ribeiro", 31},
    {"Raimundo Melo", 50},
    {"Helena Campos", 36},
    {"Isabel Costa", 49},
    {"Rebeca Machado", 26},
    {"Theo Monteiro", 49},
    {"Enzo Mendes", 46},
    {"Isabella Ferreira", 71},
    {"Theo Pinto", 77},
    {"Joana Fernandes", 52},
    {"Lorena Araujo", 41},
    {"Sergio Campos", 68},
    {"Lucas Barbosa", 22},
    {"Francisco Almeida", 33},
    {"Daniel Costa", 63},
    {"Francisco Peixoto", 58},
    {"Isabel Martins", 23},
    {"Beatriz Peixoto", 53},
    {"Nicolas Campos", 44},
    {"Gael Rocha", 32},
    {"Laura Martins", 57},
    {"Enzo Vieira", 47},
    {"Francisco Viana", 55},
    {"Joao Rocha", 43},
    {"Sophia Costa", 68},
    {"Cecilia Melo", 25},
    {"Nicolas Cunha", 59},
    {"Gabriel Machado", 66},
    {"Davi Costa", 77},
    {"Isabel Rezende", 55},
    {"Theo Martins", 66},
    {"Joao Rezende", 51},
    {"Francisco Cunha", 42},
    {"Rafael Lima", 72},
    {"Roberto Rezende", 28},
    {"Rodrigo Lopes", 27},
    {"Rafael Machado", 74},
    {"Livia Azevedo", 71},
    {"Manuela Moreira", 42},
    {"Theo Castro", 63},
    {"Arthur Nascimento", 50},
    {"Guilherme Teixeira", 62},
    {"Julia Siqueira", 49},
    {"Daniel Barbosa", 25},
    {"Isabel Cardoso", 30},
    {"Manuela Viana", 34},
    {"Alice Carvalho", 33},
    {"Manuela Carvalho", 52},
    {"Livia Borges", 65},
    {"Daniel Carvalho", 48},
    {"Helena Cardoso", 34},
    {"Lorena Cunha", 33},
    {"Cecilia Peixoto", 28},
    {"Isabella Cunha", 46},
    {"Theo Alves", 46},
    {"Helena Dias", 54},
    {"Leticia Martins", 73},
    {"Nicolas Castro", 59},
    {"Theo Siqueira", 62},
    {"Leticia Monteiro", 26},
    {"Bernardo Souza", 66},
    {"Patricia Ribeiro", 47},
    {"Debora Melo", 31},
    {"Raimundo Cunha", 59},
    {"Enzo Melo", 79},
    {"Lorena Gomes", 25},
    {"Manuela Campos", 49},
    {"Gael Lopes", 32},
    {"Gabriel Almeida", 57},
    {"Eloa Ferreira", 40},
    {"Livia Cardoso", 57},
    {"Maria Rocha", 43},
    {"Ricardo Viana", 65},
    {"Livia Rezende", 21},
    {"Daniel Martins", 29},
    {"Sofia Ferreira", 71},
    {"Sergio Neves", 75},
    {"Agatha Peixoto", 41},
    {"Matheus Araujo", 33},
    {"Gabriel Azevedo", 26},
    {"Sofia Almeida", 33},
    {"Antonio Araujo", 72},
    {"Yasmin Ferreira", 22},
    {"Luiza Monteiro", 35},
    {"Fernando Tavares", 22},
    {"Isabella Campos", 55},
    {"Lucas Azevedo", 42},
    {"Guilherme Guedes", 55},
    {"Marcos Siqueira", 49},
    {"Theo Ferreira", 53},
    {"Laura Borges", 38},
    {"Gael Neves", 72},
    {"Guilherme Ferreira", 39},
    {"Rebeca Martins", 63},
    {"Daniel Santos", 52},
    {"Alice Melo", 58},
    {"Isabella Araujo", 39},
    {"Ricardo Ferreira", 25},
    {"Joao Costa", 75},
    {"Raimundo Costa", 47},
    {"Bernardo Pinto", 28},
    {"Livia Costa", 63},
    {"Andre Martins", 78},
    {"Roberto Siqueira", 25},
    {"Rodrigo Machado", 63},
    {"Laura Ferreira", 54},
    {"Laura Azevedo", 30},
    {"Heloisa Borges", 24},
    {"Paulo Campos", 72},
    {"Emanuelly Fernandes", 52},
    {"Isabel Ferreira", 25},
    {"Alice Ribeiro", 62},
    {"Sergio Viana", 60},
    {"Sergio Martins", 33},
    {"Sophia Ferreira", 32},
    {"Helena Fernandes", 23},
    {"Lorena Lopes", 29},
    {"Patricia Almeida", 40},
    {"Davi Dias", 58},
    {"Livia Gomes", 53},
    {"Eloa Costa", 74},
    {"Isabel Almeida", 66},
    {"Paulo Rezende", 77},
    {"Raimundo Martins", 20},
    {"Leticia Cunha", 59},
    {"Patricia Mendes", 43},
    {"Rodrigo Castro", 28},
    {"Thiago Siqueira", 50},
    {"Carla Martins", 42},
    {"Miguel Campos", 70},
    {"Cecilia Castro", 63},
    {"Ricardo Ribeiro", 48},
    {"Luiza Almeida", 74},
    {"Leticia Rocha", 24},
    {"Isabella Costa", 54},
    {"Francisco Ferreira", 28},
    {"Heloisa Campos", 49},
    {"Bernardo Guedes", 29},
    {"Cecilia Pinto", 43},
    {"Sergio Dias", 40},
    {"Daniel Teixeira", 26},
    {"Raimundo Rocha", 37},
    {"Ricardo Rocha", 53},
    {"Samuel Alves", 55},
    {"Daniel Cunha", 44},
    {"Isabella Rezende", 75},
    {"Lorena Peixoto", 27},
    {"Sophia Campos", 48},
    {"Fatima Lopes", 69},
    {"Arthur Borges", 24},
    {"Lucas Ribeiro", 21},
    {"Gael Santos", 61},
    {"Francisco Mendes", 48},
    {"Heloisa Siqueira", 22},
    {"Patricia Souza", 22},
    {"Luiza Costa", 27},
    {"Agatha Ferreira", 72},
    {"Enzo Borges", 67},
    {"Guilherme Lopes", 63},
    {"Francisco Castro", 63},
    {"Heitor Araujo", 62},
    {"Livia Viana", 22},
    {"Heloisa Lopes", 66},
    {"Daniel Campos", 72},
    {"Lucas Almeida", 60},
    {"Matheus Pinto", 49},
    {"Joana Rezende", 51},
    {"Manuela Siqueira", 59},
    {"Lucas Gomes", 20},
    {"Luiza Santos", 21},
    {"Ricardo Dias", 37},
    {"Emanuelly Melo", 59},
    {"Debora Almeida", 56},
    {"Davi Siqueira", 57},
    {"Heitor Martins", 57},
    {"Joao Azevedo", 73},
    {"Sergio Santos", 53},
    {"Laura Almeida", 49},
    {"Rodrigo Cunha", 23},
    {"Laura Santos", 67},
    {"Antonio Siqueira", 23},
    {"Enzo Martins", 23},
    {"Laura Campos", 51},
    {"Laura Gomes", 31},
    {"Joao Mendes", 28},
    {"Luiza Araujo", 41},
    {"Arthur Fernandes", 25},
    {"Thiago Tavares", 72},
    {"Theo Dias", 66},
    {"Guilherme Santos", 40},
    {"Isabel Melo", 30},
    {"Rafael Peixoto", 71},
    {"Helena Ribeiro", 20},
    {"Debora Souza", 28},
    {"Helena Araujo", 64},
    {"Ricardo Cunha", 66},
    {"Carlos Cardoso", 39},
    {"Daniel Almeida", 26},
    {"Fernando Rezende", 73},
    {"Livia Siqueira", 71},
    {"Maria Castro", 63},
    {"Davi Melo", 56},
    {"Lucas Cunha", 20},
    {"Emanuelly Ribeiro", 48},
    {"Andre Tavares", 79},
    {"Thiago Rocha", 73},
    {"Thiago Almeida", 67},
    {"Alice Campos", 50},
    {"Raimundo Dias", 30},
    {"Debora Tavares", 40},
    {"Gael Dias", 67},
    {"Valentina Castro", 60},
    {"Isabel Araujo", 45},
    {"Sofia Rezende", 59},
    {"Heloisa Melo", 22},
    {"Paulo Melo", 56},
    {"Joao Viana", 78},
    {"Helena Siqueira", 21},
    {"Miguel Cardoso", 22},
    {"Sophia Viana", 34},
    {"Raimundo Araujo", 33},
    {"Gael Tavares", 55},
    {"Theo Rezende", 34},
    {"Lucas Ferreira", 38},
    {"Joao Campos", 46},
    {"Patricia Rocha", 28},
    {"Matheus Siqueira", 47},
    {"Luiza Cunha", 37},
    {"Roberto Mendes", 41},
    {"Alice Dias", 38},
    {"Gael Cunha", 79},
    {"Guilherme Martins", 49},
    {"Sofia Lopes", 22},
    {"Marcos Campos", 55},
    {"Heitor Teixeira", 35},
    {"Francisco Dias", 20},
    {"Gael Ferreira", 51},
    {"Rebeca Azevedo", 30},
    {"Carla Peixoto", 27},
    {"Rodrigo Ribeiro", 65},
    {"Gael Carvalho", 58},
    {"Cecilia Siqueira", 31},
    {"Matheus Teixeira", 35},
    {"Helena Castro", 45},
    {"Luiza Melo", 31},
    {"Thiago Peixoto", 38},
    {"Leticia Peixoto", 22},
    {"Livia Ferreira", 59},
    {"Rebeca Siqueira", 24},
    {"Gael Martins", 31},
    {"Bernardo Melo", 54},
    {"Emanuelly Rocha", 27},
    {"Heloisa Viana", 78},
    {"Carla Campos", 28},
    {"Rafael Souza", 62},
    {"Andre Cunha", 52},
    {"Davi Martins", 79},
    {"Rebeca Cunha", 45},
    {"Sophia Cunha", 76},
    {"Heloisa Dias", 32},
    {"Enzo Siqueira", 52},
    {"Marcos Castro", 59},
    {"Rafael Castro", 26},
    {"Maria Almeida", 71},
    {"Lucas Siqueira", 67},
    {"Emanuelly Santos", 56},
    {"Emanuelly Siqueira", 59},
    {"Isabel Gomes", 27},
    {"Raimundo Campos", 72},
    {"Joana Santos", 41},
    {"Fatima Santos", 22},
    {"Luiza Rezende", 69},
    {"Theo Mendes", 37},
    {"Heitor Viana", 41},
    {"Carla Ribeiro", 49},
    {"Thiago Melo", 78},
    {"Agatha Ribeiro", 37},
    {"Heloisa Araujo", 40},
    {"Paulo Santos", 25},
    {"Manuela Peixoto", 31},
    {"Carlos Campos", 40},
    {"Davi Cunha", 28},
    {"Alice Castro", 39},
    {"Miguel Melo", 51},
    {"Bernardo Santos", 47},
    {"Guilherme Melo", 43},
    {"Guilherme Cardoso", 34},
    {"Sofia Siqueira", 76},
    {"Theo Almeida", 21},
    {"Isabel Campos", 79},
    {"Gael Ribeiro", 58},
    {"Andre Dias", 48},
    {"Agatha Lopes", 61},
    {"Bernardo Castro", 31},
    {"Rafael Campos", 68},
    {"Heitor Peixoto", 24},
    {"Sergio Siqueira", 51},
    {"Manuela Rezende", 71},
    {"Ricardo Melo", 29},
    {"Davi Araujo", 42},
    {"Matheus Lopes", 32},
    {"Lucas Melo", 57},
    {"Livia Almeida", 57},
    {"Carla Siqueira", 39},
    {"Livia Santos", 48},
    {"Paulo Ribeiro", 45},
    {"Leticia Melo", 63},
    {"Sergio Ribeiro", 25},
    {"Eloa Martins", 26},
    {"Patricia Cunha", 75},
    {"Helena Martins", 34},
    {"Gael Melo", 37},
    {"Joao Martins", 76},
    {"Lucas Cardoso", 66},
    {"Luiza Peixoto", 65},
    {"Paulo Lopes", 30},
    {"Rodrigo Mendes", 46},
    {"Heitor Siqueira", 33},
    {"Andre Melo", 22},
    {"Joana Siqueira", 48},
    {"Alice Santos", 63},
    {"Bernardo Dias", 46},
    {"Roberto Castro", 55},
    {"Heitor Melo", 52},
    {"Luiza Dias", 22},
    {"Raimundo Siqueira", 27},
    {"Felipe Martins", 66},
    {"Valentina Rezende", 79},
    {"Patricia Martins", 36},
    {"Enzo Castro", 30},
    {"Joao Melo", 49},
    {"Roberto Campos", 75},
    {"Marcos Dias", 28},
    {"Heloisa Rezende", 38},
    {"Sergio Almeida", 51},
    {"Helena Santos", 71},
    {"Gabriel Santos", 37},
    {"Rafael Dias", 78},
    {"Fatima Melo", 44},
    {"Livia Cunha", 64},
    {"Livia Ribeiro", 55},
    {"Davi Lopes", 50},
    {"Guilherme Dias", 53},
    {"Maria Campos", 36},
    {"Carla Cunha", 76},
    {"Rebeca Melo", 28},
    {"Valentina Dias", 67},
    {"Leticia Campos", 53},
    {"Sergio Castro", 59},
    {"Patricia Siqueira", 50},
    {"Cecilia Campos", 20},
    {"Guilherme Castro", 71},
    {"Rafael Melo", 33},
    {"Luiza Siqueira", 67},
    {"Lucas Martins", 58},
    {"Luiza Martins", 42},
    {"Antonio Melo", 49},
    {"Alice Ferreira", 71},
    {"Fatima Ferreira", 22},
    {"Theo Santos", 20},
    {"Bernardo Martins", 43},
    {"Patricia Campos", 55},
    {"Enzo Lopes", 26},
    {"Rodrigo Martins", 51},
    {"Lucas Santos", 57},
    {"Isabella Lopes", 76},
    {"Arthur Melo", 46},
    {"Joana Martins", 27},
    {"Francisco Campos", 42},
    {"Agatha Siqueira", 52},
    {"Felipe Siqueira", 30},
    {"Enzo Almeida", 33},
    {"Francisco Siqueira", 54},
    {"Matheus Martins", 63},
    {"Alice Rezende", 79},
    {"Matheus Santos", 47},
    {"Raimundo Ribeiro", 24},
    {"Livia Campos", 25},
    {"Paulo Martins", 55},
    {"Debora Martins", 65},
    {"Daniel Melo", 47},
    {"Maria Martins", 58},
    {"Valentina Siqueira", 58},
    {"Helena Cunha", 71},
    {"Roberto Dias", 23},
    {"Cecilia Dias", 40},
    {"Joao Siqueira", 33},
    {"Isabel Dias", 72},
    {"Felipe Dias", 45},
    {"Fatima Martins", 48},
    {"Lucas Lopes", 35},
    {"Luiza Campos", 43},
    {"Fatima Campos", 57},
    {"Roberto Melo", 29},
    {"Andre Siqueira", 46},
    {"Raimundo Santos", 64},
    {"Guilherme Cunha", 68},
    {"Joana Campos", 51},
    {"Francisco Martins", 53},
    {"Patricia Dias", 49},
    {"Alice Siqueira", 79},
    {"Heitor Santos", 56},
    {"Heloisa Martins", 23},
    {"Gael Campos", 36},
    {"Rodrigo Siqueira", 78},
    {"Laura Siqueira", 73},
    {"Theo Viana", 22},
    {"Maria Melo", 73},
    {"Guilherme Rezende", 75},
    {"Carlos Martins", 21},
    {"Rafael Siqueira", 39},
    {"Rebeca Campos", 33},
    {"Laura Martins", 58},
    {"Ricardo Martins", 21},
    {"Heloisa Santos", 50},
    {"Marcos Melo", 36},
    {"Ricardo Campos", 29},
    {"Isabella Martins", 60},
    {"Gabriel Martins", 77},
    {"Rodrigo Dias", 70},
    {"Heitor Dias", 69},
    {"Gael Almeida", 66},
    {"Raimundo Melo", 55},
    {"Enzo Dias", 59},
    {"Matheus Melo", 33},
    {"Sergio Melo", 50},
    {"Sophia Siqueira", 74},
    {"Bernardo Siqueira", 49},
    {"Maria Siqueira", 33},
    {"Alice Martins", 44},
    {"Felipe Campos", 60},
    {"Matheus Campos", 24},
    {"Sergio Lopes", 79},
    {"Raimundo Lopes", 59},
    {"Felipe Lopes", 47},
    {"Bernardo Campos", 35},
    {"Isabella Siqueira", 45},
    {"Bernardo Rezende", 46},
    {"Guilherme Siqueira", 67},
    {"Guilherme Campos", 52},
    {"Joao Dias", 26},
    {"Carlos Siqueira", 59},
    {"Carlos Dias", 66},
    {"Heitor Campos", 77},
    {"Bernardo Almeida", 28},
    {"Roberto Santos", 51},
    {"Davi Santos", 67},
    {"Marcos Martins", 76},
    {"Heitor Lopes", 69},
    {"Laura Lopes", 73},
    {"Enzo Campos", 73},
    {"Marcos Santos", 25},
    {"Felipe Melo", 59},
    {"Isabel Santos", 75},
    {"Raimundo Martins", 56},
    {"Heitor Almeida", 56},
    {"Paulo Siqueira", 72},
    {"Rodrigo Santos", 22},
    {"Ricardo Siqueira", 62},
    {"Lucas Dias", 44},
    {"Rebeca Dias", 57},
    {"Sophia Martins", 53},
    {"Gael Siqueira", 66},
    {"Helena Lopes", 48},
    {"Marcos Lopes", 73},
    {"Bernardo Lopes", 77},
    {"Lucas Campos", 51},
    {"Sergio Campos", 21},
    {"Felipe Santos", 63},
    {"Livia Martins", 49},
    {"Carlos Melo", 53},
    {"Daniel Siqueira", 49},
    {"Raimundo Dias", 35},
    {"Andre Lopes", 36},
    {"Paulo Dias", 70},
    {"Gael Lopes", 45},
    {"Heitor Martins", 58},
    {"Livia Santos", 35},
    {"Raimundo Siqueira", 49},
    {"Roberto Martins", 47},
    {"Joao Santos", 41},
    {"Laura Siqueira", 34},
    {"Bernardo Martins", 60},
    {"Gabriel Campos", 70},
    {"Marcos Siqueira", 65},
    {"Guilherme Almeida", 29},
    {"Davi Dias", 56},
    {"Raimundo Campos", 76},
    {"Isabella Dias", 62},
    {"Roberto Siqueira", 69},
    {"Enzo Siqueira", 49},
    {"Ricardo Santos", 43},
    {"Maria Santos", 21},
    {"Alice Lopes", 28},
    {"Rafael Martins", 55},
    {"Theo Martins", 49},
    {"Livia Dias", 65},
    {"Felipe Dias", 49},
    {"Roberto Lopes", 52},
    {"Rodrigo Lopes", 60},
    {"Matheus Dias", 24},
    {"Ricardo Lopes", 72},
    {"Enzo Martins", 20},
    {"Paulo Campos", 74},
    {"Paulo Santos", 29},
    {"Joao Lopes", 52},
    {"Marcos Campos", 50},
    {"Andre Santos", 60},
    {"Theo Santos", 41},
    {"Rodrigo Campos", 21},
    {"Matheus Santos", 27},
    {"Andre Martins", 77},
    {"Felipe Martins", 42},
    {"Davi Siqueira", 26},
    {"Gabriel Martins", 75},
    {"Livia Campos", 49},
    {"Laura Santos", 30},
    {"Heitor Siqueira", 64},
    {"Davi Lopes", 55},
    {"Ricardo Martins", 75},
    {"Rafael Santos", 56},
    {"Carlos Santos", 79},
    {"Gael Martins", 63},
    {"Isabella Santos", 27},
    {"Lucas Siqueira", 68},
    {"Matheus Martins", 29},
    {"Enzo Santos", 47},
    {"Gabriel Siqueira", 65},
    {"Davi Martins", 68},
    {"Bernardo Siqueira", 71},
    {"Carlos Martins", 56},
    {"Joao Martins", 28},
    {"Gabriel Lopes", 70},
    {"Roberto Campos", 73},
    {"Laura Martins", 51},
    {"Daniel Santos", 50},
    {"Gael Santos", 62},
    {"Theo Siqueira", 56},
    {"Theo Lopes", 63},
    {"Bernardo Santos", 49},
    {"Davi Santos", 68},
    {"Carlos Siqueira", 44},
    {"Rafael Campos", 67},
    {"Gael Campos", 71},
    {"Lucas Martins", 48},
    {"Felipe Siqueira", 53},
    {"Enzo Lopes", 37},
    {"Daniel Martins", 28},
    {"Matheus Siqueira", 71},
    {"Heitor Campos", 74},
    {"Gabriel Santos", 39},
    {"Sergio Siqueira", 61},
    {"Joao Siqueira", 50},
    {"Bernardo Campos", 32},
    {"Rafael Siqueira", 64},
    {"Enzo Campos", 77},
    {"Roberto Santos", 42},
    {"Ricardo Siqueira", 31},
    {"Gael Siqueira", 41},
    {"Rodrigo Siqueira", 58},
    {"Theo Campos", 64},
    {"Daniel Campos", 44},
    {"Matheus Campos", 26},
    {"Rodrigo Martins", 57},
    {"Heitor Santos", 53},
    {"Daniel Siqueira", 66},
    {"Felipe Campos", 65},
    {"Lucas Santos", 61},
    {"Ricardo Campos", 28},
    {"Sergio Santos", 46},
    {"Guilherme Siqueira", 38},
    {"Davi Campos", 32},
    {"Guilherme Campos", 55},
    {"Theo Martins", 62},
    {"Paulo Siqueira", 67},
    {"Joao Campos", 31},
    {"Roberto Martins", 76},
    {"Livia Siqueira", 43},
    {"Guilherme Santos", 30},
    {"Lucas Lopes", 36},
    {"Bernardo Martins", 40},
    {"Felipe Lopes", 49},
    {"Carlos Campos", 35},
    {"Andre Campos", 62},
    {"Rodrigo Santos", 26},
    {"Marcos Santos", 32},
    {"Gabriel Lopes", 45},
    {"Rafael Lopes", 52},
    {"Joao Lopes", 42},
    {"Heitor Lopes", 64},
    {"Ricardo Santos", 58},
    {"Sergio Martins", 34},
    {"Rafael Martins", 42},
    {"Gael Lopes", 33},
    {"Guilherme Martins", 61},
    {"Enzo Dias", 41},
    {"Roberto Dias", 70},
    {"Sophia Campos", 65},
    {"Andre Siqueira", 77},
    {"Marcos Martins", 77},
    {"Enzo Almeida", 66},
    {"Gabriel Almeida", 56},
    {"Davi Almeida", 74},
    {"Rodrigo Almeida", 30},
    {"Sergio Almeida", 61},
    {"Livia Almeida", 35},
    {"Heitor Almeida", 51},
    {"Sophia Almeida", 49},
    {"Theo Almeida", 56},
    {"Matheus Almeida", 64},
    {"Carlos Almeida", 52},
    {"Marcos Almeida", 56},
    {"Helena Almeida", 67},
    {"Alice Almeida", 51},
    {"Gael Almeida", 26},
    {"Ricardo Almeida", 76},
    {"Lucas Almeida", 65},
    {"Roberto Almeida", 33},
    {"Bernardo Almeida", 56},
    {"Daniel Almeida", 27},
    {"Felipe Almeida", 36},
    {"Rafael Almeida", 21},
    {"Guilherme Almeida", 76},
    {"Joao Almeida", 42},
    {"Enzo Siqueira", 51},
    {"Rodrigo Siqueira", 40},
    {"Heitor Siqueira", 73},
    {"Livia Siqueira", 79},
    {"Theo Siqueira", 25},
    {"Carlos Siqueira", 46},
    {"Davi Siqueira", 62},
    {"Roberto Siqueira", 36},
    {"Sergio Siqueira", 22},
    {"Gael Siqueira", 33},
    {"Ricardo Siqueira", 32},
    {"Sophia Siqueira", 73},
    {"Matheus Siqueira", 42},
    {"Helena Siqueira", 77},
    {"Alice Siqueira", 29},
    {"Guilherme Siqueira", 63},
    {"Felipe Siqueira", 75},
    {"Lucas Siqueira", 44},
    {"Bernardo Siqueira", 22},
    {"Marcos Siqueira", 39},
    {"Joao Siqueira", 73},
    {"Daniel Siqueira", 56},
    {"Gabriel Siqueira", 43},
    {"Rafael Siqueira", 50},
    {"Andre Siqueira", 21},
    {"Paulo Siqueira", 57},
    {"Paulo Campos", 78},
    {"Davi Campos", 62},
    {"Felipe Campos", 66},
    {"Roberto Campos", 74},
    {"Sergio Campos", 65},
    {"Helena Campos", 48},
    {"Gael Campos", 72},
    {"Gabriel Campos", 35},
    {"Bernardo Campos", 73},
    {"Alice Campos", 59},
    {"Rodrigo Campos", 39},
    {"Livia Campos", 20},
    {"Joao Campos", 49},
    {"Heitor Campos", 39},
    {"Guilherme Campos", 78},
    {"Sophia Campos", 39},
    {"Ricardo Campos", 71},
    {"Andre Campos", 55},
    {"Daniel Campos", 78},
    {"Matheus Campos", 57},
    {"Carlos Campos", 39},
    {"Theo Campos", 49},
    {"Lucas Campos", 33},
    {"Marcos Campos", 56},
    {"Rafael Campos", 23},
    {"Enzo Campos", 71},
    {"Lucas Santos", 44},
    {"Enzo Santos", 40},
    {"Carlos Santos", 76},
    {"Davi Santos", 70},
    {"Bernardo Santos", 78},
    {"Sergio Santos", 72},
    {"Theo Santos", 49},
    {"Andre Santos", 73},
    {"Daniel Santos", 51},
    {"Roberto Santos", 27},
    {"Felipe Santos", 29},
    {"Rodrigo Santos", 31},
    {"Marcos Santos", 28},
    {"Rafael Santos", 40},
    {"Matheus Santos", 48},
    {"Gabriel Santos", 51},
    {"Heitor Santos", 77},
    {"Guilherme Santos", 75},
    {"Ricardo Santos", 68},
    {"Paulo Santos", 48},
    {"Helena Santos", 28},
    {"Gael Santos", 29},
    {"Joao Santos", 46},
    {"Livia Santos", 36},
    {"Alice Santos", 33},
    {"Sophia Santos", 59},
    {"Heitor Martins", 34},
    {"Paulo Martins", 47},
    {"Livia Martins", 68},
    {"Sergio Martins", 68},
    {"Rodrigo Martins", 20},
    {"Rafael Martins", 47},
    {"Sophia Martins", 63},
    {"Roberto Martins", 20},
    {"Felipe Martins", 46},
    {"Gabriel Martins", 29},
    {"Theo Martins", 76},
    {"Marcos Martins", 49},
    {"Ricardo Martins", 79},
    {"Enzo Martins", 73},
    {"Andre Martins", 72},
    {"Bernardo Martins", 55},
    {"Carlos Martins", 22},
    {"Davi Martins", 69},
    {"Matheus Martins", 62},
    {"Daniel Martins", 34},
    {"Lucas Martins", 30},
    {"Alice Martins", 48},
    {"Joao Martins", 44},
    {"Gael Martins", 62},
    {"Helena Martins", 22},
    {"Guilherme Martins", 40},
    {"Gael Dias", 25},
    {"Ricardo Dias", 36},
    {"Guilherme Dias", 54},
    {"Theo Dias", 34},
    {"Davi Dias", 31},
    {"Roberto Dias", 22},
    {"Andre Dias", 29},
    {"Alice Dias", 30},
    {"Daniel Dias", 69},
    {"Paulo Dias", 63},
    {"Sophia Dias", 45},
    {"Lucas Dias", 23},
    {"Marcos Dias", 47},
    {"Sergio Dias", 64},
    {"Helena Dias", 55},
    {"Rafael Dias", 25},
    {"Rodrigo Dias", 73},
    {"Joao Dias", 22},
    {"Carlos Dias", 61},
    {"Matheus Dias", 36},
    {"Gabriel Dias", 52},
    {"Heitor Dias", 62},
    {"Bernardo Dias", 56},
    {"Enzo Dias", 30},
    {"Felipe Dias", 64},
    {"Livia Dias", 28},
    {"Livia Lopes", 39},
    {"Felipe Lopes", 24},
    {"Gabriel Lopes", 62},
    {"Carlos Lopes", 68},
    {"Joao Lopes", 27},
    {"Matheus Lopes", 29},
    {"Ricardo Lopes", 50},
    {"Paulo Lopes", 23},
    {"Sergio Lopes", 23},
    {"Andre Lopes", 37},
    {"Sophia Lopes", 62},
    {"Roberto Lopes", 50},
    {"Heitor Lopes", 68},
    {"Davi Lopes", 45},
    {"Daniel Lopes", 75},
    {"Rodrigo Lopes", 69},
    {"Theo Lopes", 61},
    {"Helena Lopes", 65},
    {"Rafael Lopes", 29},
    {"Gael Lopes", 39},
    {"Marcos Lopes", 77},
    {"Alice Lopes", 21},
    {"Enzo Lopes", 67},
    {"Bernardo Lopes", 78},
    {"Guilherme Lopes", 72},
    {"Lucas Lopes", 38},
    {"Theo Melo", 63},
    {"Marcos Melo", 23},
    {"Paulo Melo", 46},
    {"Alice Melo", 50},
    {"Davi Melo", 30},
    {"Helena Melo", 20},
    {"Guilherme Melo", 48},
    {"Sergio Melo", 31},
    {"Felipe Melo", 79},
    {"Gael Melo", 64},
    {"Ricardo Melo", 24},
    {"Rodrigo Melo", 69},
    {"Livia Melo", 67},
    {"Carlos Melo", 50},
    {"Gabriel Melo", 29},
    {"Matheus Melo", 54},
    {"Andre Melo", 31},
    {"Roberto Melo", 24},
    {"Joao Melo", 45},
    {"Heitor Melo", 53},
    {"Lucas Melo", 60},
    {"Daniel Melo", 73},
    {"Rafael Melo", 79},
    {"Enzo Melo", 70},
    {"Bernardo Melo", 51},
    {"Sophia Melo", 20},
    {"Joao Rezende", 24},
    {"Roberto Rezende", 63},
    {"Theo Rezende", 24},
    {"Sophia Rezende", 69},
    {"Felipe Rezende", 74},
    {"Rodrigo Rezende", 34},
    {"Heitor Rezende", 69},
    {"Gabriel Rezende", 28},
    {"Rafael Rezende", 45},
    {"Sergio Rezende", 68},
    {"Marcos Rezende", 39},
    {"Carlos Rezende", 37},
    {"Andre Rezende", 28},
    {"Alice Rezende", 39},
    {"Ricardo Rezende", 75},
    {"Davi Rezende", 31},
    {"Helena Rezende", 59},
    {"Daniel Rezende", 51},
    {"Gael Rezende", 36},
    {"Matheus Rezende", 33},
    {"Paulo Rezende", 25},
    {"Enzo Rezende", 31},
    {"Livia Rezende", 78},
    {"Bernardo Rezende", 35},
    {"Guilherme Rezende", 73},
    {"Lucas Rezende", 28},
    {"Rodrigo Ribeiro", 75},
    {"Ricardo Ribeiro", 78},
    {"Enzo Ribeiro", 56},
    {"Felipe Ribeiro", 48},
    {"Roberto Ribeiro", 62},
    {"Rafael Ribeiro", 41},
    {"Carlos Ribeiro", 24},
    {"Andre Ribeiro", 65},
    {"Daniel Ribeiro", 50},
    {"Paulo Ribeiro", 44},
    {"Livia Ribeiro", 20},
    {"Helena Ribeiro", 55},
    {"Gael Ribeiro", 53},
    {"Davi Ribeiro", 73},
    {"Gabriel Ribeiro", 34},
    {"Heitor Ribeiro", 41},
    {"Theo Ribeiro", 63},
    {"Lucas Ribeiro", 59},
    {"Matheus Ribeiro", 38},
    {"Guilherme Ribeiro", 53},
    {"Marcos Ribeiro", 62},
    {"Sergio Ribeiro", 77},
    {"Alice Ribeiro", 73},
    {"Joao Ribeiro", 20},
    {"Bernardo Ribeiro", 36},
    {"Sophia Ribeiro", 43},
    {"Lucas Siqueira", 46},
    {"Andre Siqueira", 67},
    {"Paulo Siqueira", 51},
    {"Felipe Siqueira", 31},
    {"Livia Siqueira", 46},
    {"Matheus Siqueira", 43},
    {"Sergio Siqueira", 57},
    {"Gabriel Siqueira", 79},
    {"Roberto Siqueira", 79},
    {"Gael Siqueira", 30},
    {"Enzo Siqueira", 69},
    {"Rafael Siqueira", 26},
    {"Joao Siqueira", 51},
    {"Rodrigo Siqueira", 71},
    {"Theo Siqueira", 74},
    {"Carlos Siqueira", 43},
    {"Bernardo Siqueira", 73},
    {"Davi Siqueira", 50},
    {"Daniel Siqueira", 33},
    {"Guilherme Siqueira", 61},
    {"Ricardo Siqueira", 56},
    {"Marcos Siqueira", 66},
    {"Alice Siqueira", 44},
    {"Helena Siqueira", 61},
    {"Sophia Siqueira", 33},
    {"Heitor Siqueira", 49},
    {"Rafael Almeida", 30},
    {"Daniel Almeida", 56},
    {"Sergio Almeida", 21},
    {"Bernardo Almeida", 26},
    {"Lucas Almeida", 24},
    {"Gael Almeida", 76},
    {"Roberto Almeida", 77},
    {"Davi Almeida", 67},
    {"Carlos Almeida", 49},
    {"Andre Almeida", 49},
    {"Joao Almeida", 48},
    {"Rodrigo Almeida", 38},
    {"Enzo Almeida", 61},
    {"Ricardo Almeida", 34},
    {"Heitor Almeida", 33},
    {"Guilherme Almeida", 78},
    {"Theo Almeida", 29},
    {"Felipe Almeida", 33},
    {"Marcos Almeida", 73},
    {"Matheus Almeida", 66},
    {"Gabriel Almeida", 50},
    {"Alice Almeida", 53},
    {"Helena Almeida", 68},
    {"Paulo Almeida", 46},
    {"Livia Almeida", 38},
    {"Sophia Almeida", 39},
    {"Sophia Campos", 77},
    {"Sergio Campos", 44},
    {"Roberto Campos", 72},
    {"Lucas Campos", 68},
    {"Gael Campos", 32},
    {"Ricardo Campos", 36},
    {"Bernardo Campos", 21},
    {"Felipe Campos", 25},
    {"Daniel Campos", 76},
    {"Theo Campos", 67},
    {"Enzo Campos", 55},
    {"Matheus Campos", 74},
    {"Paulo Campos", 23},
    {"Davi Campos", 66},
    {"Gabriel Campos", 67},
    {"Carlos Campos", 33},
    {"Alice Campos", 73},
    {"Heitor Campos", 70},
    {"Andre Campos", 76},
    {"Rodrigo Campos", 22},
    {"Livia Campos", 29},
    {"Helena Campos", 49},
    {"Guilherme Campos", 77},
    {"Rafael Campos", 64},
    {"Marcos Campos", 70},
    {"Joao Campos", 28},
    {"Carlos Santos", 31},
    {"Sergio Santos", 55},
    {"Gabriel Santos", 20},
    {"Enzo Santos", 37},
    {"Bernardo Santos", 41},
    {"Gael Santos", 68},
    {"Theo Santos", 40},
    {"Rodrigo Santos", 66},
    {"Heitor Santos", 64},
    {"Matheus Santos", 49},
    {"Lucas Santos", 43},
    {"Rafael Santos", 44},
    {"Joao Santos", 77},
    {"Roberto Santos", 52},
    {"Ricardo Santos", 67},
    {"Daniel Santos", 49},
    {"Andre Santos", 63},
    {"Davi Santos", 44},
    {"Felipe Santos", 35},
    {"Guilherme Santos", 47},
    {"Marcos Santos", 29},
    {"Paulo Santos", 26},
    {"Sophia Santos", 53},
    {"Livia Santos", 71},
    {"Alice Santos", 38},
    {"Helena Santos", 26},
    {"Carlos Dias", 36},
    {"Matheus Dias", 37},
    {"Gabriel Dias", 22},
    {"Heitor Dias", 54},
    {"Ricardo Dias", 76},
    {"Joao Dias", 23},
    {"Gael Dias", 69},
    {"Andre Dias", 22},
    {"Sergio Dias", 29},
    {"Felipe Dias", 44},
    {"Lucas Dias", 78},
    {"Davi Dias", 34},
    {"Rodrigo Dias", 31},
    {"Paulo Dias", 36},
    {"Theo Dias", 60},
    {"Roberto Dias", 62},
    {"Enzo Dias", 48},
    {"Bernardo Dias", 53},
    {"Guilherme Dias", 78},
    {"Daniel Dias", 28},
    {"Marcos Dias", 29},
    {"Rafael Dias", 73},
    {"Helena Dias", 58},
    {"Sophia Dias", 48},
    {"Livia Dias", 71},
    {"Alice Dias", 39},
    {"Bernardo Martins", 42},
    {"Enzo Martins", 21},
    {"Lucas Martins", 57},
    {"Felipe Martins", 76},
    {"Gael Martins", 29},
    {"Marcos Martins", 40},
    {"Daniel Martins", 69},
    {"Paulo Martins", 20},
    {"Sergio Martins", 33},
    {"Guilherme Martins", 57},
    {"Gabriel Martins", 66},
    {"Carlos Martins", 23},
    {"Andre Martins", 49},
    {"Rodrigo Martins", 59},
    {"Davi Martins", 23},
    {"Roberto Martins", 43},
    {"Ricardo Martins", 72},
    {"Joao Martins", 26},
    {"Rafael Martins", 69},
    {"Matheus Martins", 61},
    {"Theo Martins", 58},
    {"Heitor Martins", 43},
    {"Sophia Martins", 58},
    {"Alice Martins", 40},
    {"Helena Martins", 41},
    {"Livia Martins", 62},
    {"Rafael Lopes", 78},
    {"Davi Lopes", 78},
    {"Daniel Lopes", 62},
    {"Joao Lopes", 50},
    {"Felipe Lopes", 20},
    {"Theo Lopes", 24},
    {"Roberto Lopes", 60},
    {"Ricardo Lopes", 45},
    {"Heitor Lopes", 47},
    {"Rodrigo Lopes", 34},
    {"Paulo Lopes", 73},
    {"Enzo Lopes", 20},
    {"Gabriel Lopes", 53},
    {"Sergio Lopes", 77},
    {"Bernardo Lopes", 71},
    {"Guilherme Lopes", 62},
    {"Gael Lopes", 37},
    {"Matheus Lopes", 30},
    {"Marcos Lopes", 54},
    {"Andre Lopes", 34},
    {"Carlos Lopes", 47},
    {"Lucas Lopes", 28},
    {"Sophia Lopes", 38},
    {"Helena Lopes", 77},
    {"Alice Lopes", 56},
    {"Livia Lopes", 25},
    {"Roberto Melo", 52},
    {"Daniel Melo", 43},
    {"Carlos Melo", 30},
    {"Heitor Melo", 70},
    {"Sergio Melo", 28},
    {"Ricardo Melo", 48},
    {"Rafael Melo", 35},
    {"Rodrigo Melo", 37},
    {"Enzo Melo", 22},
    {"Davi Melo", 50},
    {"Gabriel Melo", 77},
    {"Paulo Melo", 41},
    {"Andre Melo", 56},
    {"Gael Melo", 76},
    {"Joao Melo", 46},
    {"Guilherme Melo", 21},
    {"Lucas Melo", 63},
    {"Matheus Melo", 57},
    {"Marcos Melo", 55},
    {"Bernardo Melo", 53},
    {"Felipe Melo", 64},
    {"Theo Melo", 68},
    {"Alice Melo", 54},
    {"Helena Melo", 23},
    {"Livia Melo", 31},
    {"Sophia Melo", 51},
    {"Rafael Rezende", 24},
    {"Ricardo Rezende", 68},
    {"Sergio Rezende", 34},
    {"Felipe Rezende", 46},
    {"Heitor Rezende", 74},
    {"Gabriel Rezende", 73},
    {"Guilherme Rezende", 65},
    {"Rodrigo Rezende", 65},
    {"Gael Rezende", 69},
    {"Andre Rezende", 71},
    {"Lucas Rezende", 72},
    {"Joao Rezende", 33},
    {"Marcos Rezende", 72},
    {"Daniel Rezende", 39},
    {"Carlos Rezende", 58},
    {"Davi Rezende", 22},
    {"Paulo Rezende", 44},
    {"Matheus Rezende", 60},
    {"Bernardo Rezende", 52},
    {"Enzo Rezende", 43},
    {"Theo Rezende", 22},
    {"Roberto Rezende", 41},
    {"Sophia Rezende", 64},
    {"Livia Rezende", 62},
    {"Helena Rezende", 72},
    {"Alice Rezende", 59},
    {"Daniel Ribeiro", 38},
    {"Theo Ribeiro", 45},
    {"Felipe Ribeiro", 71},
    {"Gael Ribeiro", 78},
    {"Rodrigo Ribeiro", 74},
    {"Andre Ribeiro", 30},
    {"Heitor Ribeiro", 33},
    {"Marcos Ribeiro", 65},
    {"Matheus Ribeiro", 27},
    {"Lucas Ribeiro", 21},
    {"Roberto Ribeiro", 79},
    {"Sergio Ribeiro", 33},
    {"Enzo Ribeiro", 77},
    {"Guilherme Ribeiro", 74},
    {"Carlos Ribeiro", 22},
    {"Gabriel Ribeiro", 25},
    {"Ricardo Ribeiro", 77},
    {"Joao Ribeiro", 26},
    {"Paulo Ribeiro", 48},
    {"Davi Ribeiro", 76},
    {"Rafael Ribeiro", 62},
    {"Bernardo Ribeiro", 62},
    {"Livia Ribeiro", 47},
    {"Sophia Ribeiro", 76},
    {"Helena Ribeiro", 27},
    {"Alice Ribeiro", 71},
};
    int n = sizeof(pessoas) / sizeof(pessoas[0]);

    
    Pessoa pessoas_bubble[n];
    Pessoa pessoas_selection[n];
    Pessoa pessoas_quick[n];

   
    int num_execucoes = 5;

    printf("Estado inicial do array:\n");
    imprimirPessoas(pessoas, n);

    Metricas metricas_bubble = {0, 0, 0.0};
    printf("Executando Bubble Sort...\n");
    int i;
    for( i = 0; i < num_execucoes; i++) {
        memcpy(pessoas_bubble, pessoas, sizeof(pessoas)); 
        clock_t inicio = clock();
        bubbleSort(pessoas_bubble, n, &metricas_bubble);
        clock_t fim = clock();
        metricas_bubble.tempo_total += ((double)(fim - inicio) * 1000.0 / CLOCKS_PER_SEC);
    }
    printf("Array ordenado pelo Bubble Sort:\n");
    imprimirPessoas(pessoas_bubble, n);
    printf("Bubble Sort - Comparacoes: %lld\n", metricas_bubble.comparacoes);
    printf("Bubble Sort - Trocas: %lld\n", metricas_bubble.trocas);
    printf("Bubble Sort - Tempo medio de execucoo: %.4f ms\n\n", metricas_bubble.tempo_total / num_execucoes);

 
    Metricas metricas_selection = {0, 0, 0.0};
    printf("Executando Selection Sort...\n");
   
    for( i = 0; i < num_execucoes; i++) {
        memcpy(pessoas_selection, pessoas, sizeof(pessoas));
        clock_t inicio = clock();
        selectionSort(pessoas_selection, n, &metricas_selection);
        clock_t fim = clock();
        metricas_selection.tempo_total += ((double)(fim - inicio) * 1000.0 / CLOCKS_PER_SEC);
    }
    printf("Array ordenado pelo Selection Sort:\n");
    imprimirPessoas(pessoas_selection, n);
    printf("Selection Sort - Comparacoes: %lld\n", metricas_selection.comparacoes);
    printf("Selection Sort - Trocas: %lld\n", metricas_selection.trocas);
    printf("Selection Sort - Tempo medio de execucao: %.4f ms\n\n", metricas_selection.tempo_total / num_execucoes);


  
    Metricas metricas_quick = {0, 0, 0.0};
    printf("Executando Quick Sort...\n");
    for( i = 0; i < num_execucoes; i++) {
        memcpy(pessoas_quick, pessoas, sizeof(pessoas));
        clock_t inicio = clock();
        quickSort(pessoas_quick, 0, n - 1, &metricas_quick);
        clock_t fim = clock();
        metricas_quick.tempo_total += ((double)(fim - inicio) * 1000.0 / CLOCKS_PER_SEC);
    }
    printf("Array ordenado pelo Quick Sort:\n");
    imprimirPessoas(pessoas_quick, n);
    printf("Quick Sort - Comparacoes: %lld\n", metricas_quick.comparacoes);
    printf("Quick Sort - Trocas: %lld\n", metricas_quick.trocas);
    printf("Quick Sort - Tempo medio de execucao: %.4f ms\n\n", metricas_quick.tempo_total / num_execucoes);

    return 0;
}
